[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
deadpool-postgres = { workspace = true }
dotenv = { workspace = true }
prost = { workspace = true }
refinery = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
tonic = { workspace = true }
tracing = {workspace = true }

shared = { version = "0.1", path = "../shared" }
rand = { version = "0.9.1", features = ["std_rng"] }
sha2 = "0.10"
base64 = { version = "0.22" }
url = "2.5.4"
