[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
deadpool-postgres = "0.14.1"
dotenv = "0.15.0"
prost = "0.11"
prost-types = { version = "0.11" }
serde = { version = "1.0", features = ["derive"] }
rand = { version = "0.9.1", features = ["std_rng"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "rt", "macros"] }
tokio-postgres = { version = "0.7", features = ["with-time-0_3", "with-chrono-0_4"] }
sha2 = "0.10"
thiserror = "2.0.12"
