services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
      PGPORT: ${PG_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data 

  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: gateway
    ports:
      - 3000:3000
    depends_on:
      - auth

  auth:
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PG_PORT=${PG_PORT}
        - PG_USER=${PG_USER}
        - PG_PASSWORD=${PG_PASSWORD}
        - PG_DBNAME=${PG_DBNAME}
      args:
        SERVICE_NAME: auth
    depends_on:
      - db

  user:
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PG_PORT=${PG_PORT}
        - PG_USER=${PG_USER}
        - PG_PASSWORD=${PG_PASSWORD}
        - PG_DBNAME=${PG_DBNAME}
      args:
        SERVICE_NAME: user
    depends_on:
      - db
      - auth
 
volumes:
  pgdata:
