version: "3.9"

services:
  gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    image: services_gateway:latest
    ports:
      - 3000:3000
    depends_on:
      - auth
      - user
    networks:
      - shared_network

  auth:
    env_file: .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./auth/Dockerfile
      args:
        - PG_PORT=${PG_PORT}
        - PG_USER=${PG_USER}
        - PG_PASSWORD=${PG_PASSWORD}
        - PG_DBNAME=auth_db
    image: services_auth:latest
    networks:
      - shared_network

  user:
    env_file: .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./user/Dockerfile
      args:
        - PG_PORT=${PG_PORT}
        - PG_USER=${PG_USER}
        - PG_PASSWORD=${PG_PASSWORD}
        - PG_DBNAME=user_db
    image: services_user:latest
    networks:
      - shared_network

networks:
  shared_network:
    external: true
